python run.py  --config-name=libero_config \
            --multirun agents=awr_agent \
            trainers=awr_trainer \
            agent_name=awr_transformer \
            group=awr_decoder_only \
            agents/model=bc/bc_dec_transformer \
            +trainset.use_returns=True \
            +trainset.discount=0.99 \
            task_suite=libero_object \
            traj_per_task=10 \
            seed=0,1,2
